### ISSUE TITLE
Tilrettelegge for flere finaler - kan ha finale c2 og b2 og evt b3

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#106]
Flere får gå 3 heat.

Bør løses etter https://github.com/langrenn-sprint/race-service/issues/20

**Comment by stigbd** [comment]
Ok, fint. Litt enklare å implementere dersom ein angir totalt antall til B-finaler. 
Altså ved 2 B-finaler, kan regelen vere 'B': 4, i staden for 'B1': 2, 'B2': 2. (Gitt at det skal vere like mange i kvar.)

**Comment by stigbd** [comment]
Har no lukkast i å lage ein generalisert raceplan-funksjon. Vi må nok ha samsvar mellom keys i `no_of_heats` og `from_to`. Så dermed må det blir som følger, eksempel:
```
 {
        "max_no_of_contestants": 32,
        "rounds": ["Q", "S", "F"],
        "no_of_heats": {"Q": {"A": 4}, "S": {"A": 2, "C": 2}, "F": {"A": 1, "B": 1, "C1": 1, "C2": 1}},
        "from_to": {"Q": {"A": {"S": {"A": 4, "C": "REST"}}}, "S": {"A": {"F": {"A": 4, "B": "REST"}}, "C": {"F": {"C1": 4, "C2": "REST"}}}}
    },
```

**Comment by stigbd** [comment]
Bra. Då har faktisk ein PR klar som støtter dette. Må berre skrive eit par testar først.

**Comment by stigbd** [comment]
@heming-langrenn Då har eg oppretta ny branch for å teste bedre rundt flere finaler scenariet.

Det eg avdekka då, var at konfigen du lagde over, resulterer i at vi lager heat med for mange løpere i. 

Eksempel: race med order=143 (G14) har 12 løpere i FC1. G14 har 49 påmeldte i klassen, så det er i følgande konfig det bli feil i dette tilfellet:
```
"max_no_of_contestants": 56,
"rounds": ["Q", "S", "F"],
"no_of_heats": {"Q": {"A": 7}, "S": {"A": 4, "C": 4}, "F": {"A": 1, "B": 3, "C": 3}},
"from_to": {"Q": {"A": {"S": {"A": 4, "C": "REST"}}}, "S": {"A": {"F": {"A": 2, "B1": 2, "B2": 2, "B3": "REST"}}, "C": {"F": {"C1": 3, "C2": 3, "C3": "REST"}}}}
```
Det er jo mulig at det er min implementasjon som er, og at konfigurasjonen er i orden.

Kan du gjere ei vurdering?

**Comment by stigbd** [comment]
Bra. Tenker vi må lage valideringsregler i competition-format-service som ganger opp disse. Eg oppretter issue.

**Comment by stigbd** [comment]
Også feil for J13 (45 deltakar), som endar opp med 'Too many contestants in race raceclass/round/indexJ13/F/C1: 16.'}.
Kofing som feiler:
```
"max_no_of_contestants": 48,
"rounds": ["Q", "S", "F"],
"no_of_heats": {"Q": {"A": 6}, "S": {"A": 4, "C": 4}, "F": {"A": 1, "B": 3, "C": 2}},
"from_to": {"Q": {"A": {"S": {"A": 4, "C": "REST"}}}, "S": {"A": {"F": {"A": 2, "B1": 2, "B2": 2, "B3": "REST"}}, "C": {"F": {"C1": 4, "C2": "REST"}}}}
```
