### ISSUE TITLE
Error - event_id mangler i service

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#114]
f"{RACE_SERVICE_URL}/races/all/start-entries?bib={bib}"

event_id må inn for å unngå at vi henter deltakere fra flere arrangement

**Comment by stigbd** [comment]
> f"{RACE_SERVICE_URL}/races/all/start-entries?bib={bib}"

Hmm... `all` path parameter er ikkje støtta av race-service. Kan du bekrefte at requesten faktisk er slik som dette, @heming-langrenn ?

Og kan du legge lenke til relevant kode inn i kommentar, slik at eg kan undersøke litt nøyare flyten her?

**Comment by stigbd** [comment]
Her er alle races-rutene i race-service:
```
/races
/races/{raceId}
/races/{raceId}/race-results
/races/{raceId}/race-results/{raceResultId}
/races/{raceId}/start-entries
/races/{raceId}/start-entries/{startEntryId}
```

**Comment by stigbd** [comment]
Foreslår å lage en egen resource for start-entry, der vi kan legge på ulike query-parameters:
```
/start-entries?eventId=<event_id>&bib=123                    # her vil eventId vere obligatorisk
/start-entries?eventId=<event_id>&startlistId=<startlist-id> # her vil eventId vere obligatorisk
/start-entries?eventId=<event_id>&raceId=<race_id>           # her vil eventId vere obligatorisk
/start-entries/{startEntryId}
```
Det burde dekke det meste. Eller har du også behov for andre queries?

**Comment by stigbd** [comment]
Kva for spørringar blir gjort _i dag_ frå front-end når det gjelder start-entries?

**Comment by heming-h** [comment]
Hei @stigbd.
Jeg ser at for det meste så hentes start-entries gjennom å spørre på race. Eneste stedet det spørres direkte på start-entries by bib er når en contestant skal endres - for å validere at ikke vi endrer en deltaker som ligger i startlisten.

Jeg kan godt fikse dette i frontend ved å søke via races, det er jo ikke en funksjon som kommer til å bli kalt veldig ofte (sikkert maks et par ganger pr renn?). Foreslår derfor enkel løsning:
1. Vi dropper å lage egen resource for start-entry.
2. Vi fjerner funksjonene på /races/{raceId}/start-entries
3. Vi fjerner get_start_entries_by_bib i https://github.com/langrenn-sprint/event-service-gui/blob/main/event_service_gui/services/start_adapter.py (som faktisk fungerer og er med /all/)
4. Vi skriver om update_contestant til å søke i startlister via races

**Comment by stigbd** [comment]
Ok. Oppfattar det dermed slik at det ikkje lenger er behov for å legge til event_id i service. Lukker.
Feilen i `GET /races/{raceId}/start-entries` der `raceId` ikkje vart brukt i spørringa mot basen, er fiksa i annan PR.
