### ISSUE TITLE
Det er mulig å legge inn duplikate resultater i race

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#122]
Vi bør ha validering på at et startnummer kun kan ha en registrering pr passeringspunkt i et race.

Plass |   | Startnr | Navn | Klubb | Aldersklasse
-- | -- | -- | -- | -- | --
1 | FA | 62 | Sigrid Winge Prytz | Kjelsås IL - Ski | J 13 år
2 | FA | 52 | Maren Aasdalen | Kjelsås IL - Ski | J 13 år
3 | FA | 54 | Lilly Kvikne Silgjerd | Kjelsås IL - Ski | J 13 år
4 | FA | 61 | Thea Pladsen Gussiås | Røa Allianseidrettslag - Ski | J 13 år
5 | FA | 63 | Ella Klaveness Walker | Røa Allianseidrettslag - Ski | J 13 år
6 | FA | 51 | Hanna Cecilia Braaten | Heming, IL - Ski | J 13 år
7 | FA | 56 | Thea Elise Torkildsen | Idrettslaget Try - Ski | J 13 år
8 | FB | 53 | Ayda Djau | Høybråten og Stovner IL - Ski | J 13 år
9 | FB | 53 | Ayda Djau | Høybråten og Stovner IL - Ski | J 13 år
10 | FB | 53 | Ayda Djau | Høybråten og Stovner IL - Ski | J 13 år
11 | FB | 53 | Ayda Djau | Høybråten og Stovner IL - Ski | J 13 år
12 | FB | 59 | Tora Bjarttun Alvenes | Bækkelagets SK - Ski | J 13 år
13 | FB | 59 | Tora Bjarttun Alvenes | Bækkelagets SK - Ski | J 13 år
14 | FB | 59 | Tora Bjarttun Alvenes | Bækkelagets SK - Ski | J 13 år
15 | FB | 59 | Tora Bjarttun Alvenes | Bækkelagets SK - Ski | J 13 år
16 | FB | 57 | Signe Kismul Fiskå | Bækkelagets SK - Ski | J 13 år
17 | FB | 57 | Signe Kismul Fiskå | Bækkelagets SK - Ski | J 13 år
18 | FB | 57 | Signe Kismul Fiskå | Bækkelagets SK - Ski | J 13 år
19 | FB | 60 | Tiril Halvorsen | Lyn Ski - Ski | J 13 år
20 | FB | 60 | Tiril Halvorsen | Lyn Ski - Ski | J 13 år
21 | FB | 60 | Tiril Halvorsen | Lyn Ski - Ski | J 13 år

Plass		Startnr	Navn	Klubb	Aldersklasse
1	FA	62	[Sigrid Winge Prytz](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=62)	 Kjelsås IL - Ski	J 13 år
2	FA	52	[Maren Aasdalen](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=52)	 Kjelsås IL - Ski	J 13 år
3	FA	54	[Lilly Kvikne Silgjerd](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=54)	 Kjelsås IL - Ski	J 13 år
4	FA	61	[Thea Pladsen Gussiås](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=61)	 Røa Allianseidrettslag - Ski	J 13 år
5	FA	63	[Ella Klaveness Walker](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=63)	 Røa Allianseidrettslag - Ski	J 13 år
6	FA	51	[Hanna Cecilia Braaten](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=51)	 Heming, IL - Ski	J 13 år
7	FA	56	[Thea Elise Torkildsen](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=56)	 Idrettslaget Try - Ski	J 13 år
8	FB	53	[Ayda Djau](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=53)	 Høybråten og Stovner IL - Ski	J 13 år
9	FB	53	[Ayda Djau](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=53)	 Høybråten og Stovner IL - Ski	J 13 år
10	FB	53	[Ayda Djau](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=53)	 Høybråten og Stovner IL - Ski	J 13 år
11	FB	53	[Ayda Djau](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=53)	 Høybråten og Stovner IL - Ski	J 13 år
12	FB	59	[Tora Bjarttun Alvenes](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=59)	 Bækkelagets SK - Ski	J 13 år
13	FB	59	[Tora Bjarttun Alvenes](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=59)	 Bækkelagets SK - Ski	J 13 år
14	FB	59	[Tora Bjarttun Alvenes](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=59)	 Bækkelagets SK - Ski	J 13 år
15	FB	59	[Tora Bjarttun Alvenes](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=59)	 Bækkelagets SK - Ski	J 13 år
16	FB	57	[Signe Kismul Fiskå](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=57)	 Bækkelagets SK - Ski	J 13 år
17	FB	57	[Signe Kismul Fiskå](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=57)	 Bækkelagets SK - Ski	J 13 år
18	FB	57	[Signe Kismul Fiskå](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=57)	 Bækkelagets SK - Ski	J 13 år
19	FB	60	[Tiril Halvorsen](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=60)	 Lyn Ski - Ski	J 13 år
20	FB	60	[Tiril Halvorsen](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=60)	 Lyn Ski - Ski	J 13 år
21	FB	60	[Tiril Halvorsen](http://localhost:8090/live?event_id=8790cffb-110f-4866-af64-95cacaabedc0&klasse=J13&startnr=60)	 Lyn Ski - Ski	J 13 år

**Comment by stigbd** [comment]
Dersom det fins en passering for gitt bib på gitt timing_point, skal vi då
a) legge til time_event og sette status til Error, eller
b) ikkje legge til time_event.

I tilfelle (a), korleis retter vi opp feile time_events?

**Comment by stigbd** [comment]
Det fins også eit tredje alternativ:
c) dersom det fins en passering for gitt bib på gitt timing_point, oppdater den eksisterende.

**Comment by stigbd** [comment]
Fixed by 51883b5
