### ISSUE TITLE
Rar valideringsfeil i generate_startlist_for_event

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#131]
{'detail': 'len(contestants) does not match number of contestants in raceplan:78 != 78.'}

**Comment by stigbd** [comment]
Punktumet er irrelevant og kjem frå backend. Feilen er at feilmeldinga i backend ikkje rapporterer korrekt tal:
https://github.com/langrenn-sprint/race-service/blob/51883b5218eb1a3c4b261468c603f316e326f96d/race_service/commands/startlists_commands.py#L86-L90

**Comment by stigbd** [comment]
Fik for feilmelding er på veg. 
@heming-langrenn Det er imidlertid interessant kva du gjorde for å få denne feilen. Kan du beskrive korleis gjenskape?
