### ISSUE TITLE
Error - 500: list.remove(x): x not in list.

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#137]
Oppstår på delete time events - {RACE_SERVICE_URL}/time-events/{id}

Trolig fordi time event har status Error eller at den ikke ligger i heat resultat?

Startnr | Heat | Passeringspunkt | Tid | Plass | Videre til | Status | Changelog
----------|------- | ---------------------- | ---- | -------- | ----------- | -------- | ------------
34 | K18-QA1 | Finish | 2022-12-25T09:49:26 | 2 | FA-2 | Error | 2022-12-25T09:49:26: 2 plass i mål. (admin)2022-12-25T09:49:28.941287+01:00: Error in time-event "Finish": Contestant with bib 34 is not in race start-entries. (race_service)

**Comment by stigbd** [comment]
Har klart å gjenskape. Loggen:
> race-service_1                | {"message": "list.remove(x): x not in list", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp_middlewares/error.py\", line 210, in middleware\n    return await handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py\", line 954, in _iter\n    resp = await method()\n  File \"/app/race_service/views/time_events.py\", line 211, in delete\n    race_result.ranking_sequence.remove(time_event_id)\nValueError: list.remove(x): x not in list", "severity": "ERROR", "serviceContext": {"service": "race-service"}}

**Comment by stigbd** [comment]
Grunnen til dette er at vi no validerer strengere på resultater (time-events) som er feil. Dette resultat vart aldri lagt til i race. Har no endra delete-logikken slik at vi ignorerer dersom fjerning feiler pga at time-events ikkje er i race-result.
