### ISSUE TITLE
query på bib i get_startlist_by_event_id

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#161]
Det kan vere du meiner "get_startlist_by_event_id"? Denne gir alle start-entries i en event. Her kan vi evt legge på en query-variabel ("bib), som filtrerer på gitt bib. Du vil då få ei liste med alle start-entries i en event som tilhøyrer gitt bib.

**Comment by stigbd** [comment]
Duplicate of #160
