### ISSUE TITLE
Add support for user supplied configuration matrix rule table for individual sprints

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/race-service#20]
The table as shown in https://github.com/langrenn-sprint/event-service/issues/49#issue-1009852195 should be user supplied and stored along with the event competition format for individual sprint formats.

**Comment by heming-langrenn** [comment]
Forslag til datasett som utgjør config - list of dicts:
    race_settings = [
        {
            "max_no_of_contestants": 8,
            "no_of_heat": {"Q": 1, "FA": 1},
            "rule": {"Q": {"FA": float("inf")}},
        },
        {
            "max_no_of_contestants": 16,
            "no_of_heat": {"Q": 2, "FA": 1, "FB": 1},
            "rule": {"Q": {"FA": 4, "FB": float("inf")}},
        },
        {
            "max_no_of_contestants": 24,
            "no_of_heat": {"Q": 3, "SA": 2, "FA": 1, "FB": 1, "FC": 1},
            "rule": {"Q": {"SA": 5, "FC": float("inf")}, "SA": {"FA": 4, "FB": 4}},
        },
        {
            "max_no_of_contestants": 32,
            "no_of_heat": {"Q": 4, "SA": 2, "SC": 2, "FA": 1, "FB": 1, "FC": 1},
            "rule": {
                "Q": {"SA": 4, "SC": float("inf")},
                "SA": {"FA": 4, "FB": 4},
                "SC": {"FC": 4},
            },
        },
        {
            "max_no_of_contestants": 80,
            "no_of_heat": {"Q": 8, "SA": 4, "SC": 4, "FA": 1, "FB": 1, "FC": 1},
            "rule": {
                "Q": {"SA": 4, "SC": float("inf")},
                "SA": {"FA": 2, "FB": 2},
                "SC": {"FC": 2},
            },
        },
    ]

**Comment by heming-langrenn** [comment]
![image](https://user-images.githubusercontent.com/56455987/159372199-f4514b9b-eb5b-49b8-b2a0-86d373d6b60c.png)
