### ISSUE TITLE
start-list resource

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#25]
url: /start-lists
        start_list = {
                "position": 1, # start position
                "bib": "414",  # start number
                "event_id": "KA1",  # event id
                "race_id": "G11KA1",  # optional input / generated race id
                "start_time": "10:01:30.12",  # optional for sprint competition
                "status": "",  # optional - started or DNS
                "change_log": "",  # optional - list of dicts { time, user_id, text }. Must be used for all updates.

            }

**Comment by stigbd** [comment]
Command to generator startlists:
/startlists/generate-startlist-for-event
