### ISSUE TITLE
Service to add one start_entry in startlist

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#34]
Example on request_body (start_entry) that should be added to a start list:
{'race_id': 'ffc9642e-7031-44b5-bd5c-c4b865035602', 'bib': '7', 'starting_position': '2', 'scheduled_start_time': '2021-10-27T18:18:00'}
Typical use-case is when a quarter final result is registered and semi final start-entry shall be created.

**Comment by heming-langrenn** [comment]
@stigbd - kan du ta en titt på denne?

**Comment by stigbd** [comment]
Jess, den blir enkel når eg får på plass #31 . Jobbar med denne no.
