### ISSUE TITLE
Endre relasjonen mellom race og startlist_id til race og liste av start_entries

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/race-service#36]
race -> startlist_id: Denne tenker eg å endre til race -> liste med referanser til start_entries. Då vil #34  lett bli realiserte ved å legge til ny start_entry på race.start_entries

I tillegg vil det vere veldig greit å hente ut startlister for kvart enkelt race. Enten ved å loope igjennom start_entries, eller ved å få alle start_entries for dette spesifike race som instanser av contestants viss ein feks gjer `GET /races/1234?includeStartList=True`

**Comment by heming-langrenn** [comment]
Veldig bra, dette vil forenkle logikken flere steder i gui :-)!
