### ISSUE TITLE
feature: Add race-results to race

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/race-service#40]
RaceResults (one pr timing point, i.e. one or more intermediate timing points and finish) should be added to the race-object.

The race-results contains time-events ordered by rank.

The race-results should be made available at `GET /races/<raceId>/results` and individually at `GET /races/<raceId>/results/<timing_point>`

**Comment by stigbd** [comment]
Tenker følgande logikk:

- når det blir lagt eit nytt time-event på eit race, vil dette bli lagt til i resultat-liste for det aktuelle timing point.
- resultat-lista sin ranking-sequence vil fortløpande vere sortert på TimeEvent.rank
- alle resultatlister for eit race ligg i Race.results

Antall og lovlige verdier for "timing_point" bør ligge i konfig på eventet antagelegvis. Typiske eksempel vil sikkert vere:

- Start
- Intermediate 1
- Intermediate 2
- Finish

**Comment by heming-langrenn** [comment]
Hei @stigbd . Behøver vi både time-event og result-event på et race? Hva vil i så fall være forskjellen på disse?
Jeg hadde sett for meg at vi genererte resultatliste pr. raceclass, eventuelt pr. ageclass?.

**Comment by stigbd** [comment]
Modellen eg jobbar med no, ser slik ut. Håpar det oppklarer relasjonen mellom race og time-events:
```
@dataclass
class ResultList(DataClassJsonMixin):
    """Data class with details about a result list."""

    id: str
    race_id: str
    timing_point: str
    no_of_contestants: int
    ranking_sequence: List[str]  # list of references to TimeEvent


@dataclass
class Race(DataClassJsonMixin):
    """Data class with details about a race."""

    id: str
    raceclass: str
    order: int
    start_time: datetime = field(
        metadata=config(
            encoder=datetime.isoformat,
            decoder=datetime.fromisoformat,
            mm_field=DateTime(format="iso"),
        )
    )
    no_of_contestants: int
    event_id: str
    raceplan_id: str
    start_entries: List[str]  # list of renferences to StartEntry
    results: List[Dict[str, str]]  # list of references to Result list pr timing point
```

**Comment by stigbd** [comment]
Dette er dei uoffisielle resultatlistene pr race. Dei offisielle resultatlistene vil bli danna på bakgrunn av disse og vil gjelde for ageclass.
(For intervalstart, vil det ikkje vere stor forskjell, sidan det er 1-til-1 mellom ageclass og race. Men for heat-start events vil det jo vere 1-til-mange mellom ageclass og race. Der kvart race har ei resultatliste.)

**Comment by stigbd** [comment]
Har endra navn frå ResultList til RaceResult.
