### ISSUE TITLE
Add support for getting start entries by event_id and bib

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#44]

**Comment by stigbd** [comment]
There are two "routes" to start-entries: either by accessing the event's startlist or by looping through all races in the event.

By using the first approach, it is straigth forward to accomplish getting start-entries by bib with the existing API. E.g. you can in the client do:

```
startlist_for_event: List[StartList] = GET /startlists?eventId=<event_id>
startlist_for_event = startlist_for_events[0]  # event has only one startlist
start_entries_by_bib: List[StartEntry] = 
     [ start_entry for start_entry in startlist_for_event["StartEntries"] if start_entry["bib"] == <bib> ]
```

Can this be a solution?

**Comment by heming-langrenn** [comment]
Yep, this is how I have done it in current version. But it means that I have to load all the start entries every time. So reason for asking was optimize processing. But, we can await this and first evaluate the performance we get. Closing issue.
