### ISSUE TITLE
Sortere resultater (finish_results) etter plassering

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#58]

**Comment by stigbd** [comment]
Eg implementerte sortering etter rank i https://github.com/langrenn-sprint/race-service/commit/46e80b1b7ad94a6f6e412a00dda2cf7472e7eb94

Men mulig at det ikkje fungerer. I kva for scenario er det dette feiler?

**Comment by heming-langrenn** [comment]
Bruker -     async with ClientSession() as session:
            async with session.get(
                f"{RACE_SERVICE_URL}/races/{race_id}", headers=headers
            ) as resp:
                logging.debug(f"get_race_by_id - got response {resp.status}")
                if resp.status == 200:
                    race = await resp.json()

**Comment by stigbd** [comment]
Eg hadde fiksa sortering på `GET /races/{raceId}/race-results`. Eg hadde oversett dette scenariet. Skal vere fiksa no i https://github.com/langrenn-sprint/race-service/pull/61

Fint om du ser over og approver viss ok.
