### ISSUE TITLE
jeg ser at det brukes "replace_one" mot mongodb - kunne en løsning vært å bruke "updtae_one" i stedet - og tillate at kun attributter som er inn parametre oppdateres? Det hadde ihvertfall vært en forenkling sett fra frontend.

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/race-service#66]
jeg ser at det brukes "replace_one" mot mongodb - kunne en løsning vært å bruke "updtae_one" i stedet - og tillate at kun attributter som er inn parametre oppdateres? Det hadde ihvertfall vært en forenkling sett fra frontend.

_Originally posted by @heming-langrenn in https://github.com/langrenn-sprint/race-service/issues/65#issuecomment-1003555967_

**Comment by heming-langrenn** [comment]
Replace_one fungerer nå. Foreslår derfor å droppe denne.
