### ISSUE TITLE
GCP - race-service kaster error

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#80]
Feilen ser ut til å komme hvert 3. minutt. Sikkert en modul som ikke er innstallert på GCP? Kan du se hvilken?

race-service_1        | ERROR:aiohttp_middlewares.error:Not Found
race-service_1        | Traceback (most recent call last):
race-service_1        |   File "/usr/local/lib/python3.9/site-packages/aiohttp_middlewares/error.py", line 208, in
 middleware
race-service_1        |     return await handler(request)
race-service_1        |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 931, in
 _handle
race-service_1        |     raise self._http_exception
race-service_1        | aiohttp.web_exceptions.HTTPNotFound: Not Found
race-service_1        | 159.89.48.65 [30/Jan/2022:21:48:53 +0000] "POST /ws/v1/cluster/apps/new-application HTTP/1
.1" 404 187 "-" "python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-1160.45.1.el7.x86_64"

**Comment by stigbd** [comment]
Dette er ein vanlig 404 error som slik logginga/error-handling er satt opp, lagar litt for mykje støy. (Du får den same "feilen" viss du gjer GET /donald-duck.)

Eg endrer litt på feilhåndtering og logginga slik at dette ser litt bedre ut.

Kva eller kven som sender `POST /ws/v1/cluster/apps/new-application` vites ikke. Men eg endrer loggen slik at ip-adressen kjem fram.
