### ISSUE TITLE
En annen returkode enn 201 når det opprettes time-event med status error

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#83]
post(
                f"{RACE_SERVICE_URL}/time-events", headers=headers, json=request_body

2022-02-01T23:35:09: 3 plass i mål. (admin)2022-02-01T22:35:11.537085: Contestant with bib 19 is not in race start-entries (race_service)
--

Denne returnerer 201 også når det opprettes en time-event med status Error. Kan det være en annen funksjonell kode 2xx slik at frontend lettere kan se at det ble opprettet en time event med error?

**Comment by stigbd** [comment]
Ja: 200 OK og returnere objektet som vart oppretta, inkl status.
