### ISSUE TITLE
Må kunne slette en race result entry

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/race-service#90]
Nå ser det ut til at det kun er mulig å slette alle resultater i et race.

**Comment by stigbd** [comment]
Modellen til race-result ser slik ut:
https://github.com/langrenn-sprint/race-service/blob/main/race_service/models/race_model.py#L11-L18

Det er mulig å slette en instans av race-result, inkl alle ranking-instanser.


Viss ein vil slette enkelt instans av ranking, betyr det å slette en gitt time-event. Sjå feks her:
https://github.com/langrenn-sprint/race-service/blob/main/tests/contract/test_time_events.py#L542-L568

**Comment by heming-langrenn** [comment]
OK - skjønner. Da vet jeg hvordan jeg skal håndtere det. Jeg ser at vi begynner å få litt kompliserte avhengigheter mellom start-entries, time events og result entries nå. Vi bør ta en runde og se på forenklings-muligheter, men det gjør vi etter Ragdesprinten :-).
